{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggflowchart
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggflowchart_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggflowchart/ggflowchart_{{ version }}.tar.gz
  sha256: fb630ed91852310684d15a92d5ba88bb00779ef4230ac88e512561226df32359

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-rlang
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-rlang
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('ggflowchart')"           # [not win]
    - "\"%R%\" -e \"library('ggflowchart')\""  # [win]

about:
  home: https://nrennie.github.io/ggflowchart/
  license: MIT
  summary: Flowcharts can be a useful way to visualise complex processes. This package uses the
    layered grammar of graphics of 'ggplot2' to create simple flowcharts.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
